add feature: cycling tabBar
marcosgriselli/SwipeableTabBarController pull request #63
Opened 2019-03-29 02:28 UTC by krgoodnews

Hi, marcostriselli.

I made the Cycling Tab Bar feature.
if set true 'isCyclingEnabled', you can swipe firstVC to lastVC. The opposite is also possible.

Thank you, master.

2019-03-29 10:13 UTC, marcosgriselli commented
@krgoodnews thanks for the PR! This is a really nice feature. Would you mind adding a couple of things? 
- A small section on the readme explaining what `isCyclingEnabled` does
- Add cycling assertions to the UI test  (I can do it or guide you if you're not sure how to tackle it)

2019-03-29 11:02 UTC, krgoodnews commented
@marcosgriselli thanks for the comment. I will modify the readme.
I have not done a UI test, but I will try it.

2019-03-29 12:07 UTC, krgoodnews commented
I do,
- A small section on the readme explaining what isCyclingEnabled does
- Add cycling assertions to the UI test (I can do it or guide you if you're not sure how to tackle it)
I hope you like it.

Thanks, @marcosgriselli

2019-03-29 13:57 UTC, marcosgriselli commented
Perfect, I'll review the PR and test the branch later today

2019-03-29 23:29 UTC, marcosgriselli commented on README.md
> +`SwipeableTabBarController` supports cycling switch tab. If you want cycling switch tab, set true `isCyclingEnabled`
```suggestion
`SwipeableTabBarController` supports cycling between the first and last tab like a carousel. Simply set `isCyclingEnabled` to `true`.
```

2019-03-29 23:30 UTC, marcosgriselli commented on README.md
> +### Enable Cycling Swipe Tab Bar
```suggestion
### Enable Cycling 
```

2019-03-29 23:43 UTC, marcosgriselli requested changes
A few minor changes in documentation. I'm also wondering if there are clearer ways to set up the calculations but I guess I can review that at another time.

2019-03-30 02:28 UTC, krgoodnews commented
I think it would be good to have some chance to share our opinions. Thank you 👍

2019-03-30 10:53 UTC, marcosgriselli approved these changes
Perfect, thanks for the changes! Closes #64

2019-03-30 10:54 UTC, merged

2019-03-30 12:49 UTC, krgoodnews commented
Thank you. I learned so much from my first contribution.
I wish there will be a better chance with you.